package v1_test

import (
	"fmt"
	"testing"

	random "github.com/erdaltsksn/random/v1"
)

func TestLorem(t *testing.T) {
	tests := []struct {
		name string
		want string
	}{
		{"Whole", fmt.Sprint(`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Est pellentesque elit ullamcorper dignissim cras. Augue eget arcu dictum varius. Pellentesque sit amet porttitor eget dolor. Sapien pellentesque habitant morbi tristique senectus et netus et. Vel turpis nunc eget lorem dolor. Congue mauris rhoncus aenean vel. Imperdiet proin fermentum leo vel orci. Neque egestas congue quisque egestas diam. Ipsum suspendisse ultrices gravida dictum fusce. Commodo viverra maecenas accumsan lacus. Ornare quam viverra orci sagittis eu volutpat odio facilisis.
Tristique sollicitudin nibh sit amet commodo. Pharetra magna ac placerat vestibulum. Felis donec et odio pellentesque diam volutpat commodo. Feugiat nibh sed pulvinar proin gravida hendrerit. Risus nullam eget felis eget nunc. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Nibh praesent tristique magna sit. Morbi tincidunt ornare massa eget egestas. Sollicitudin nibh sit amet commodo nulla. Nunc sed velit dignissim sodales ut eu sem. Cras ornare arcu dui vivamus arcu felis bibendum ut. Tempus imperdiet nulla malesuada pellentesque elit eget. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Magna fringilla urna porttitor rhoncus dolor purus non enim. At risus viverra adipiscing at in tellus integer feugiat. A cras semper auctor neque. Consectetur libero id faucibus nisl tincidunt eget nullam non. Eu mi bibendum neque egestas congue quisque egestas diam in.
Nunc faucibus a pellentesque sit amet. Luctus venenatis lectus magna fringilla. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Amet est placerat in egestas erat. Erat imperdiet sed euismod nisi. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Eu nisl nunc mi ipsum. Tortor at risus viverra adipiscing at in tellus integer feugiat. Metus vulputate eu scelerisque felis imperdiet proin. Feugiat pretium nibh ipsum consequat nisl vel. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. A condimentum vitae sapien pellentesque. Amet commodo nulla facilisi nullam vehicula ipsum a. Mauris ultrices eros in cursus turpis massa. Tristique senectus et netus et. Leo integer malesuada nunc vel risus commodo viverra. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Euismod elementum nisi quis eleifend quam adipiscing vitae proin.
Ut ornare lectus sit amet est. Cras pulvinar mattis nunc sed blandit. Quam elementum pulvinar etiam non quam. Proin fermentum leo vel orci porta non. Diam quis enim lobortis scelerisque fermentum dui faucibus. Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Elementum facilisis leo vel fringilla. Malesuada bibendum arcu vitae elementum. Pharetra convallis posuere morbi leo urna molestie at elementum. Ultricies leo integer malesuada nunc. Maecenas sed enim ut sem viverra aliquet eget sit amet. Elementum nibh tellus molestie nunc non blandit massa enim nec. Eu non diam phasellus vestibulum lorem sed risus. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Nullam non nisi est sit amet facilisis. Ornare arcu dui vivamus arcu felis bibendum ut tristique.
Dictumst quisque sagittis purus sit amet volutpat. Id consectetur purus ut faucibus pulvinar elementum integer. At in tellus integer feugiat scelerisque varius. Vitae auctor eu augue ut lectus arcu bibendum at varius. Velit scelerisque in dictum non consectetur a erat nam at. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Euismod in pellentesque massa placerat duis ultricies lacus sed. Purus sit amet luctus venenatis lectus magna. Gravida dictum fusce ut placerat. Viverra adipiscing at in tellus integer feugiat. Viverra nibh cras pulvinar mattis nunc sed blandit. Dignissim sodales ut eu sem integer. Suscipit tellus mauris a diam maecenas sed. Auctor augue mauris augue neque. Non tellus orci ac auctor augue mauris augue neque gravida. Hendrerit gravida rutrum quisque non. Ac turpis egestas sed tempus urna et pharetra pharetra.
Erat pellentesque adipiscing commodo elit at imperdiet dui. Arcu non odio euismod lacinia at quis risus sed vulputate. Sodales neque sodales ut etiam sit amet nisl. Augue interdum velit euismod in pellentesque. Sagittis orci a scelerisque purus semper eget duis at. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Risus quis varius quam quisque id diam vel quam. Lacus viverra vitae congue eu consequat ac. Non quam lacus suspendisse faucibus interdum. Platea dictumst vestibulum rhoncus est. Et netus et malesuada fames ac turpis egestas. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Sed blandit libero volutpat sed. Et netus et malesuada fames ac. Porttitor eget dolor morbi non arcu risus quis varius quam.
Lacus sed viverra tellus in hac. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Aliquam purus sit amet luctus venenatis. Id consectetur purus ut faucibus pulvinar elementum. Est sit amet facilisis magna etiam tempor orci eu lobortis. Ipsum dolor sit amet consectetur adipiscing elit. Feugiat vivamus at augue eget arcu dictum varius. Urna neque viverra justo nec ultrices dui. Fermentum iaculis eu non diam. Mollis aliquam ut porttitor leo a diam sollicitudin. Diam sollicitudin tempor id eu. Ultrices dui sapien eget mi proin sed libero enim sed. Consequat mauris nunc congue nisi vitae suscipit tellus. Lobortis scelerisque fermentum dui faucibus. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Morbi tristique senectus et netus. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Eu scelerisque felis imperdiet proin fermentum.
Pellentesque id nibh tortor id aliquet. Faucibus a pellentesque sit amet porttitor eget dolor. Netus et malesuada fames ac turpis egestas. Curabitur gravida arcu ac tortor dignissim. Et tortor consequat id porta nibh venenatis. Sed vulputate odio ut enim blandit. Sapien eget mi proin sed libero. Gravida quis blandit turpis cursus. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Arcu felis bibendum ut tristique et. Eget nunc scelerisque viverra mauris in. Iaculis nunc sed augue lacus viverra vitae congue eu. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Sagittis purus sit amet volutpat consequat mauris. Mus mauris vitae ultricies leo integer malesuada nunc vel. Ullamcorper morbi tincidunt ornare massa eget egestas. Sem et tortor consequat id porta nibh venenatis cras sed. Et netus et malesuada fames ac turpis egestas sed.
Diam volutpat commodo sed egestas. Orci nulla pellentesque dignissim enim sit amet venenatis. Tempor nec feugiat nisl pretium fusce id velit. Malesuada fames ac turpis egestas sed tempus urna. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Tincidunt id aliquet risus feugiat in. Integer feugiat scelerisque varius morbi enim nunc faucibus. Magnis dis parturient montes nascetur ridiculus. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Risus pretium quam vulputate dignissim suspendisse in est ante in. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Id semper risus in hendrerit gravida rutrum quisque non tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis.
Nisi scelerisque eu ultrices vitae auctor eu augue. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Aliquam nulla facilisi cras fermentum odio. Pellentesque habitant morbi tristique senectus et. Orci sagittis eu volutpat odio. Turpis in eu mi bibendum neque egestas. Arcu risus quis varius quam quisque id diam vel quam. Volutpat est velit egestas dui id ornare.`)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := random.Lorem()
			t.Run(tt.name, func(t *testing.T) {
				if got != tt.want {
					t.Error("Got:", got, "Want", tt.want)
				}
			})
		})
	}
}

func TestLoremParagraph(t *testing.T) {
	type args struct {
		count int
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{"Zero", args{count: 0}, ""},
		{"One Paragraph", args{count: 1}, fmt.Sprint(`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Est pellentesque elit ullamcorper dignissim cras. Augue eget arcu dictum varius. Pellentesque sit amet porttitor eget dolor. Sapien pellentesque habitant morbi tristique senectus et netus et. Vel turpis nunc eget lorem dolor. Congue mauris rhoncus aenean vel. Imperdiet proin fermentum leo vel orci. Neque egestas congue quisque egestas diam. Ipsum suspendisse ultrices gravida dictum fusce. Commodo viverra maecenas accumsan lacus. Ornare quam viverra orci sagittis eu volutpat odio facilisis.`)},
		{"Two Paragraph", args{count: 2}, fmt.Sprint(`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Est pellentesque elit ullamcorper dignissim cras. Augue eget arcu dictum varius. Pellentesque sit amet porttitor eget dolor. Sapien pellentesque habitant morbi tristique senectus et netus et. Vel turpis nunc eget lorem dolor. Congue mauris rhoncus aenean vel. Imperdiet proin fermentum leo vel orci. Neque egestas congue quisque egestas diam. Ipsum suspendisse ultrices gravida dictum fusce. Commodo viverra maecenas accumsan lacus. Ornare quam viverra orci sagittis eu volutpat odio facilisis.
Tristique sollicitudin nibh sit amet commodo. Pharetra magna ac placerat vestibulum. Felis donec et odio pellentesque diam volutpat commodo. Feugiat nibh sed pulvinar proin gravida hendrerit. Risus nullam eget felis eget nunc. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Nibh praesent tristique magna sit. Morbi tincidunt ornare massa eget egestas. Sollicitudin nibh sit amet commodo nulla. Nunc sed velit dignissim sodales ut eu sem. Cras ornare arcu dui vivamus arcu felis bibendum ut. Tempus imperdiet nulla malesuada pellentesque elit eget. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Magna fringilla urna porttitor rhoncus dolor purus non enim. At risus viverra adipiscing at in tellus integer feugiat. A cras semper auctor neque. Consectetur libero id faucibus nisl tincidunt eget nullam non. Eu mi bibendum neque egestas congue quisque egestas diam in.`)},
		{"10< Paragraph", args{count: 13}, fmt.Sprint(`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Est pellentesque elit ullamcorper dignissim cras. Augue eget arcu dictum varius. Pellentesque sit amet porttitor eget dolor. Sapien pellentesque habitant morbi tristique senectus et netus et. Vel turpis nunc eget lorem dolor. Congue mauris rhoncus aenean vel. Imperdiet proin fermentum leo vel orci. Neque egestas congue quisque egestas diam. Ipsum suspendisse ultrices gravida dictum fusce. Commodo viverra maecenas accumsan lacus. Ornare quam viverra orci sagittis eu volutpat odio facilisis.
Tristique sollicitudin nibh sit amet commodo. Pharetra magna ac placerat vestibulum. Felis donec et odio pellentesque diam volutpat commodo. Feugiat nibh sed pulvinar proin gravida hendrerit. Risus nullam eget felis eget nunc. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Nibh praesent tristique magna sit. Morbi tincidunt ornare massa eget egestas. Sollicitudin nibh sit amet commodo nulla. Nunc sed velit dignissim sodales ut eu sem. Cras ornare arcu dui vivamus arcu felis bibendum ut. Tempus imperdiet nulla malesuada pellentesque elit eget. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Magna fringilla urna porttitor rhoncus dolor purus non enim. At risus viverra adipiscing at in tellus integer feugiat. A cras semper auctor neque. Consectetur libero id faucibus nisl tincidunt eget nullam non. Eu mi bibendum neque egestas congue quisque egestas diam in.
Nunc faucibus a pellentesque sit amet. Luctus venenatis lectus magna fringilla. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Amet est placerat in egestas erat. Erat imperdiet sed euismod nisi. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Eu nisl nunc mi ipsum. Tortor at risus viverra adipiscing at in tellus integer feugiat. Metus vulputate eu scelerisque felis imperdiet proin. Feugiat pretium nibh ipsum consequat nisl vel. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. A condimentum vitae sapien pellentesque. Amet commodo nulla facilisi nullam vehicula ipsum a. Mauris ultrices eros in cursus turpis massa. Tristique senectus et netus et. Leo integer malesuada nunc vel risus commodo viverra. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Euismod elementum nisi quis eleifend quam adipiscing vitae proin.
Ut ornare lectus sit amet est. Cras pulvinar mattis nunc sed blandit. Quam elementum pulvinar etiam non quam. Proin fermentum leo vel orci porta non. Diam quis enim lobortis scelerisque fermentum dui faucibus. Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Elementum facilisis leo vel fringilla. Malesuada bibendum arcu vitae elementum. Pharetra convallis posuere morbi leo urna molestie at elementum. Ultricies leo integer malesuada nunc. Maecenas sed enim ut sem viverra aliquet eget sit amet. Elementum nibh tellus molestie nunc non blandit massa enim nec. Eu non diam phasellus vestibulum lorem sed risus. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Nullam non nisi est sit amet facilisis. Ornare arcu dui vivamus arcu felis bibendum ut tristique.
Dictumst quisque sagittis purus sit amet volutpat. Id consectetur purus ut faucibus pulvinar elementum integer. At in tellus integer feugiat scelerisque varius. Vitae auctor eu augue ut lectus arcu bibendum at varius. Velit scelerisque in dictum non consectetur a erat nam at. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Euismod in pellentesque massa placerat duis ultricies lacus sed. Purus sit amet luctus venenatis lectus magna. Gravida dictum fusce ut placerat. Viverra adipiscing at in tellus integer feugiat. Viverra nibh cras pulvinar mattis nunc sed blandit. Dignissim sodales ut eu sem integer. Suscipit tellus mauris a diam maecenas sed. Auctor augue mauris augue neque. Non tellus orci ac auctor augue mauris augue neque gravida. Hendrerit gravida rutrum quisque non. Ac turpis egestas sed tempus urna et pharetra pharetra.
Erat pellentesque adipiscing commodo elit at imperdiet dui. Arcu non odio euismod lacinia at quis risus sed vulputate. Sodales neque sodales ut etiam sit amet nisl. Augue interdum velit euismod in pellentesque. Sagittis orci a scelerisque purus semper eget duis at. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Risus quis varius quam quisque id diam vel quam. Lacus viverra vitae congue eu consequat ac. Non quam lacus suspendisse faucibus interdum. Platea dictumst vestibulum rhoncus est. Et netus et malesuada fames ac turpis egestas. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Sed blandit libero volutpat sed. Et netus et malesuada fames ac. Porttitor eget dolor morbi non arcu risus quis varius quam.
Lacus sed viverra tellus in hac. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Aliquam purus sit amet luctus venenatis. Id consectetur purus ut faucibus pulvinar elementum. Est sit amet facilisis magna etiam tempor orci eu lobortis. Ipsum dolor sit amet consectetur adipiscing elit. Feugiat vivamus at augue eget arcu dictum varius. Urna neque viverra justo nec ultrices dui. Fermentum iaculis eu non diam. Mollis aliquam ut porttitor leo a diam sollicitudin. Diam sollicitudin tempor id eu. Ultrices dui sapien eget mi proin sed libero enim sed. Consequat mauris nunc congue nisi vitae suscipit tellus. Lobortis scelerisque fermentum dui faucibus. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Morbi tristique senectus et netus. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Eu scelerisque felis imperdiet proin fermentum.
Pellentesque id nibh tortor id aliquet. Faucibus a pellentesque sit amet porttitor eget dolor. Netus et malesuada fames ac turpis egestas. Curabitur gravida arcu ac tortor dignissim. Et tortor consequat id porta nibh venenatis. Sed vulputate odio ut enim blandit. Sapien eget mi proin sed libero. Gravida quis blandit turpis cursus. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Arcu felis bibendum ut tristique et. Eget nunc scelerisque viverra mauris in. Iaculis nunc sed augue lacus viverra vitae congue eu. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Sagittis purus sit amet volutpat consequat mauris. Mus mauris vitae ultricies leo integer malesuada nunc vel. Ullamcorper morbi tincidunt ornare massa eget egestas. Sem et tortor consequat id porta nibh venenatis cras sed. Et netus et malesuada fames ac turpis egestas sed.
Diam volutpat commodo sed egestas. Orci nulla pellentesque dignissim enim sit amet venenatis. Tempor nec feugiat nisl pretium fusce id velit. Malesuada fames ac turpis egestas sed tempus urna. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Tincidunt id aliquet risus feugiat in. Integer feugiat scelerisque varius morbi enim nunc faucibus. Magnis dis parturient montes nascetur ridiculus. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Risus pretium quam vulputate dignissim suspendisse in est ante in. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Id semper risus in hendrerit gravida rutrum quisque non tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis.
Nisi scelerisque eu ultrices vitae auctor eu augue. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Aliquam nulla facilisi cras fermentum odio. Pellentesque habitant morbi tristique senectus et. Orci sagittis eu volutpat odio. Turpis in eu mi bibendum neque egestas. Arcu risus quis varius quam quisque id diam vel quam. Volutpat est velit egestas dui id ornare.`)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := random.LoremParagraph(tt.args.count)
			t.Run(tt.name, func(t *testing.T) {
				if got != tt.want {
					t.Error("Got:", got, "Want", tt.want)
				}
			})
		})
	}
}

func TestLoremSentence(t *testing.T) {
	type args struct {
		count int
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{"Zero", args{count: 0}, ""},
		{"One Sentence", args{count: 1}, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."},
		{"Two Sentences", args{count: 2}, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo."},
		{"154< Sentences", args{count: 155}, fmt.Sprint(`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Est pellentesque elit ullamcorper dignissim cras. Augue eget arcu dictum varius. Pellentesque sit amet porttitor eget dolor. Sapien pellentesque habitant morbi tristique senectus et netus et. Vel turpis nunc eget lorem dolor. Congue mauris rhoncus aenean vel. Imperdiet proin fermentum leo vel orci. Neque egestas congue quisque egestas diam. Ipsum suspendisse ultrices gravida dictum fusce. Commodo viverra maecenas accumsan lacus. Ornare quam viverra orci sagittis eu volutpat odio facilisis.
Tristique sollicitudin nibh sit amet commodo. Pharetra magna ac placerat vestibulum. Felis donec et odio pellentesque diam volutpat commodo. Feugiat nibh sed pulvinar proin gravida hendrerit. Risus nullam eget felis eget nunc. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Nibh praesent tristique magna sit. Morbi tincidunt ornare massa eget egestas. Sollicitudin nibh sit amet commodo nulla. Nunc sed velit dignissim sodales ut eu sem. Cras ornare arcu dui vivamus arcu felis bibendum ut. Tempus imperdiet nulla malesuada pellentesque elit eget. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Magna fringilla urna porttitor rhoncus dolor purus non enim. At risus viverra adipiscing at in tellus integer feugiat. A cras semper auctor neque. Consectetur libero id faucibus nisl tincidunt eget nullam non. Eu mi bibendum neque egestas congue quisque egestas diam in.
Nunc faucibus a pellentesque sit amet. Luctus venenatis lectus magna fringilla. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Amet est placerat in egestas erat. Erat imperdiet sed euismod nisi. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Eu nisl nunc mi ipsum. Tortor at risus viverra adipiscing at in tellus integer feugiat. Metus vulputate eu scelerisque felis imperdiet proin. Feugiat pretium nibh ipsum consequat nisl vel. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. A condimentum vitae sapien pellentesque. Amet commodo nulla facilisi nullam vehicula ipsum a. Mauris ultrices eros in cursus turpis massa. Tristique senectus et netus et. Leo integer malesuada nunc vel risus commodo viverra. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Euismod elementum nisi quis eleifend quam adipiscing vitae proin.
Ut ornare lectus sit amet est. Cras pulvinar mattis nunc sed blandit. Quam elementum pulvinar etiam non quam. Proin fermentum leo vel orci porta non. Diam quis enim lobortis scelerisque fermentum dui faucibus. Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Elementum facilisis leo vel fringilla. Malesuada bibendum arcu vitae elementum. Pharetra convallis posuere morbi leo urna molestie at elementum. Ultricies leo integer malesuada nunc. Maecenas sed enim ut sem viverra aliquet eget sit amet. Elementum nibh tellus molestie nunc non blandit massa enim nec. Eu non diam phasellus vestibulum lorem sed risus. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Nullam non nisi est sit amet facilisis. Ornare arcu dui vivamus arcu felis bibendum ut tristique.
Dictumst quisque sagittis purus sit amet volutpat. Id consectetur purus ut faucibus pulvinar elementum integer. At in tellus integer feugiat scelerisque varius. Vitae auctor eu augue ut lectus arcu bibendum at varius. Velit scelerisque in dictum non consectetur a erat nam at. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Euismod in pellentesque massa placerat duis ultricies lacus sed. Purus sit amet luctus venenatis lectus magna. Gravida dictum fusce ut placerat. Viverra adipiscing at in tellus integer feugiat. Viverra nibh cras pulvinar mattis nunc sed blandit. Dignissim sodales ut eu sem integer. Suscipit tellus mauris a diam maecenas sed. Auctor augue mauris augue neque. Non tellus orci ac auctor augue mauris augue neque gravida. Hendrerit gravida rutrum quisque non. Ac turpis egestas sed tempus urna et pharetra pharetra.
Erat pellentesque adipiscing commodo elit at imperdiet dui. Arcu non odio euismod lacinia at quis risus sed vulputate. Sodales neque sodales ut etiam sit amet nisl. Augue interdum velit euismod in pellentesque. Sagittis orci a scelerisque purus semper eget duis at. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Risus quis varius quam quisque id diam vel quam. Lacus viverra vitae congue eu consequat ac. Non quam lacus suspendisse faucibus interdum. Platea dictumst vestibulum rhoncus est. Et netus et malesuada fames ac turpis egestas. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Sed blandit libero volutpat sed. Et netus et malesuada fames ac. Porttitor eget dolor morbi non arcu risus quis varius quam.
Lacus sed viverra tellus in hac. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Aliquam purus sit amet luctus venenatis. Id consectetur purus ut faucibus pulvinar elementum. Est sit amet facilisis magna etiam tempor orci eu lobortis. Ipsum dolor sit amet consectetur adipiscing elit. Feugiat vivamus at augue eget arcu dictum varius. Urna neque viverra justo nec ultrices dui. Fermentum iaculis eu non diam. Mollis aliquam ut porttitor leo a diam sollicitudin. Diam sollicitudin tempor id eu. Ultrices dui sapien eget mi proin sed libero enim sed. Consequat mauris nunc congue nisi vitae suscipit tellus. Lobortis scelerisque fermentum dui faucibus. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Morbi tristique senectus et netus. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Eu scelerisque felis imperdiet proin fermentum.
Pellentesque id nibh tortor id aliquet. Faucibus a pellentesque sit amet porttitor eget dolor. Netus et malesuada fames ac turpis egestas. Curabitur gravida arcu ac tortor dignissim. Et tortor consequat id porta nibh venenatis. Sed vulputate odio ut enim blandit. Sapien eget mi proin sed libero. Gravida quis blandit turpis cursus. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Arcu felis bibendum ut tristique et. Eget nunc scelerisque viverra mauris in. Iaculis nunc sed augue lacus viverra vitae congue eu. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Sagittis purus sit amet volutpat consequat mauris. Mus mauris vitae ultricies leo integer malesuada nunc vel. Ullamcorper morbi tincidunt ornare massa eget egestas. Sem et tortor consequat id porta nibh venenatis cras sed. Et netus et malesuada fames ac turpis egestas sed.
Diam volutpat commodo sed egestas. Orci nulla pellentesque dignissim enim sit amet venenatis. Tempor nec feugiat nisl pretium fusce id velit. Malesuada fames ac turpis egestas sed tempus urna. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Tincidunt id aliquet risus feugiat in. Integer feugiat scelerisque varius morbi enim nunc faucibus. Magnis dis parturient montes nascetur ridiculus. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Risus pretium quam vulputate dignissim suspendisse in est ante in. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Id semper risus in hendrerit gravida rutrum quisque non tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis.
Nisi scelerisque eu ultrices vitae auctor eu augue. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Aliquam nulla facilisi cras fermentum odio. Pellentesque habitant morbi tristique senectus et. Orci sagittis eu volutpat odio. Turpis in eu mi bibendum neque egestas. Arcu risus quis varius quam quisque id diam vel quam. Volutpat est velit egestas dui id ornare.`)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := random.LoremSentence(tt.args.count)
			t.Run(tt.name, func(t *testing.T) {
				if got != tt.want {
					t.Error("Got:", got, "Want", tt.want)
				}
			})
		})
	}
}

func TestLoremCharacter(t *testing.T) {
	type args struct {
		count int
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{"Zero", args{count: 0}, ""},
		{"One Character", args{count: 1}, "L"},
		{"Two Characters", args{count: 2}, "Lo"},
		{"With Space", args{count: 6}, "Lorem "},
		{"80000< Characters", args{count: 80000}, fmt.Sprint(`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Est pellentesque elit ullamcorper dignissim cras. Augue eget arcu dictum varius. Pellentesque sit amet porttitor eget dolor. Sapien pellentesque habitant morbi tristique senectus et netus et. Vel turpis nunc eget lorem dolor. Congue mauris rhoncus aenean vel. Imperdiet proin fermentum leo vel orci. Neque egestas congue quisque egestas diam. Ipsum suspendisse ultrices gravida dictum fusce. Commodo viverra maecenas accumsan lacus. Ornare quam viverra orci sagittis eu volutpat odio facilisis.
Tristique sollicitudin nibh sit amet commodo. Pharetra magna ac placerat vestibulum. Felis donec et odio pellentesque diam volutpat commodo. Feugiat nibh sed pulvinar proin gravida hendrerit. Risus nullam eget felis eget nunc. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Nibh praesent tristique magna sit. Morbi tincidunt ornare massa eget egestas. Sollicitudin nibh sit amet commodo nulla. Nunc sed velit dignissim sodales ut eu sem. Cras ornare arcu dui vivamus arcu felis bibendum ut. Tempus imperdiet nulla malesuada pellentesque elit eget. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Magna fringilla urna porttitor rhoncus dolor purus non enim. At risus viverra adipiscing at in tellus integer feugiat. A cras semper auctor neque. Consectetur libero id faucibus nisl tincidunt eget nullam non. Eu mi bibendum neque egestas congue quisque egestas diam in.
Nunc faucibus a pellentesque sit amet. Luctus venenatis lectus magna fringilla. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Amet est placerat in egestas erat. Erat imperdiet sed euismod nisi. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Eu nisl nunc mi ipsum. Tortor at risus viverra adipiscing at in tellus integer feugiat. Metus vulputate eu scelerisque felis imperdiet proin. Feugiat pretium nibh ipsum consequat nisl vel. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. A condimentum vitae sapien pellentesque. Amet commodo nulla facilisi nullam vehicula ipsum a. Mauris ultrices eros in cursus turpis massa. Tristique senectus et netus et. Leo integer malesuada nunc vel risus commodo viverra. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Euismod elementum nisi quis eleifend quam adipiscing vitae proin.
Ut ornare lectus sit amet est. Cras pulvinar mattis nunc sed blandit. Quam elementum pulvinar etiam non quam. Proin fermentum leo vel orci porta non. Diam quis enim lobortis scelerisque fermentum dui faucibus. Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Elementum facilisis leo vel fringilla. Malesuada bibendum arcu vitae elementum. Pharetra convallis posuere morbi leo urna molestie at elementum. Ultricies leo integer malesuada nunc. Maecenas sed enim ut sem viverra aliquet eget sit amet. Elementum nibh tellus molestie nunc non blandit massa enim nec. Eu non diam phasellus vestibulum lorem sed risus. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Nullam non nisi est sit amet facilisis. Ornare arcu dui vivamus arcu felis bibendum ut tristique.
Dictumst quisque sagittis purus sit amet volutpat. Id consectetur purus ut faucibus pulvinar elementum integer. At in tellus integer feugiat scelerisque varius. Vitae auctor eu augue ut lectus arcu bibendum at varius. Velit scelerisque in dictum non consectetur a erat nam at. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Euismod in pellentesque massa placerat duis ultricies lacus sed. Purus sit amet luctus venenatis lectus magna. Gravida dictum fusce ut placerat. Viverra adipiscing at in tellus integer feugiat. Viverra nibh cras pulvinar mattis nunc sed blandit. Dignissim sodales ut eu sem integer. Suscipit tellus mauris a diam maecenas sed. Auctor augue mauris augue neque. Non tellus orci ac auctor augue mauris augue neque gravida. Hendrerit gravida rutrum quisque non. Ac turpis egestas sed tempus urna et pharetra pharetra.
Erat pellentesque adipiscing commodo elit at imperdiet dui. Arcu non odio euismod lacinia at quis risus sed vulputate. Sodales neque sodales ut etiam sit amet nisl. Augue interdum velit euismod in pellentesque. Sagittis orci a scelerisque purus semper eget duis at. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Risus quis varius quam quisque id diam vel quam. Lacus viverra vitae congue eu consequat ac. Non quam lacus suspendisse faucibus interdum. Platea dictumst vestibulum rhoncus est. Et netus et malesuada fames ac turpis egestas. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Sed blandit libero volutpat sed. Et netus et malesuada fames ac. Porttitor eget dolor morbi non arcu risus quis varius quam.
Lacus sed viverra tellus in hac. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Aliquam purus sit amet luctus venenatis. Id consectetur purus ut faucibus pulvinar elementum. Est sit amet facilisis magna etiam tempor orci eu lobortis. Ipsum dolor sit amet consectetur adipiscing elit. Feugiat vivamus at augue eget arcu dictum varius. Urna neque viverra justo nec ultrices dui. Fermentum iaculis eu non diam. Mollis aliquam ut porttitor leo a diam sollicitudin. Diam sollicitudin tempor id eu. Ultrices dui sapien eget mi proin sed libero enim sed. Consequat mauris nunc congue nisi vitae suscipit tellus. Lobortis scelerisque fermentum dui faucibus. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Morbi tristique senectus et netus. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Eu scelerisque felis imperdiet proin fermentum.
Pellentesque id nibh tortor id aliquet. Faucibus a pellentesque sit amet porttitor eget dolor. Netus et malesuada fames ac turpis egestas. Curabitur gravida arcu ac tortor dignissim. Et tortor consequat id porta nibh venenatis. Sed vulputate odio ut enim blandit. Sapien eget mi proin sed libero. Gravida quis blandit turpis cursus. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Arcu felis bibendum ut tristique et. Eget nunc scelerisque viverra mauris in. Iaculis nunc sed augue lacus viverra vitae congue eu. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Sagittis purus sit amet volutpat consequat mauris. Mus mauris vitae ultricies leo integer malesuada nunc vel. Ullamcorper morbi tincidunt ornare massa eget egestas. Sem et tortor consequat id porta nibh venenatis cras sed. Et netus et malesuada fames ac turpis egestas sed.
Diam volutpat commodo sed egestas. Orci nulla pellentesque dignissim enim sit amet venenatis. Tempor nec feugiat nisl pretium fusce id velit. Malesuada fames ac turpis egestas sed tempus urna. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Tincidunt id aliquet risus feugiat in. Integer feugiat scelerisque varius morbi enim nunc faucibus. Magnis dis parturient montes nascetur ridiculus. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Risus pretium quam vulputate dignissim suspendisse in est ante in. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Id semper risus in hendrerit gravida rutrum quisque non tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis.
Nisi scelerisque eu ultrices vitae auctor eu augue. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Aliquam nulla facilisi cras fermentum odio. Pellentesque habitant morbi tristique senectus et. Orci sagittis eu volutpat odio. Turpis in eu mi bibendum neque egestas. Arcu risus quis varius quam quisque id diam vel quam. Volutpat est velit egestas dui id ornare.`)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := random.LoremCharacter(tt.args.count)
			t.Run(tt.name, func(t *testing.T) {
				if got != tt.want {
					t.Error("Got:", got, "Want", tt.want)
				}
			})
		})
	}
}
