before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
- main:
  env:
  - CGO_ENABLED=0
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
  goos:
  - darwin
  - linux
  - windows
  ldflags: -s -w -X {{ replace .GitURL "https://" ""}}/cmd.version={{.Tag}}

brews:
  - github:
      owner: erdaltsksn
      name: homebrew-tap
    folder: Formula
    homepage: "{{ .GitURL }}"
    description: Random data generator AKA faker
