name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - name: Check out code into $GITHUB_WORKSPACE directory
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        go build -v ./...

    - name: Test
      run: |
        go test -v ./...
